### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by TarVK** [LaunchMenu/LaunchMenu#1]
Continuation of discussion in
TarVK/Yoke#1

**Comment by zularizal** [comment]
Hi @TarVK , this is the design logo for this project. This logo is inspired by the letter L, shortcut arrows and keyboard keys. And also I made several logo display options. What do you like?

What do you think? if there is something you want to change, let me know.

![bitmap2](https://user-images.githubusercontent.com/38547278/55623976-b7cc2680-57ce-11e9-80d7-f88327998b9f.png)

**Comment by sancarn** [comment]
Cool design @zularizal discussing with Tar we both like 1 and 2 the most :)

**Comment by zularizal** [comment]
Hi @sancarn , Hi, I have sent a pull request for you. #2 

And also I have uploaded logos and icons in format vectors (.svg .eps .pdf and .ai) to the drive. Please check this link. 
https://drive.google.com/open?id=1AapHuJ2XVsmtofsBhIDBKCinclJfC8rS

**Comment by sancarn** [comment]
Thanks for this zularizal! These are great! We'll be modifying the readme in due course. Thanks!
