### ISSUE TITLE
Escape hides window in certain scenarios where it shouldn't

### ISSUE THREAD

**Issue by sancarn** [LaunchMenu/LaunchMenu#146]
This only occurs if `Hide when losing focus` setting is set to `false`:

**To reproduce the issue:**
```
* Open LM with meta+space
* Type "hello"
* Shift focus to another window
* Open LM with meta+space (query is still present)
* Press escape //you will notice LaunchMenu hides (and clears the field) rather than just only clearing the field.
```

**What I expected:**
```
* Open LM with meta+space
* Type "hello"
* Shift focus to another window
* Open LM with meta+space (query is still present)
* Press escape //search field is cleared
* Press escape //hide LM
```

**Comment by TarVK** [comment]
Can't reproduce this, what OS are you experiencing this on?

**Comment by sancarn** [comment]
Mac

**Comment by TarVK** [comment]
Guess this will be a debug task for you then :P
I can't reproduce on windows, and don't have a Mac to test it on myself.

**Comment by sancarn** [comment]
I can't actually reproduce this anymore... Closing, but might still be an issue for some people
