### ISSUE TITLE
CTRL + Backspace or Delete is not working in input

### ISSUE THREAD

**Issue by bramhoven** [LaunchMenu/LaunchMenu#147]
**Describe the bug**
When using the input in LM you cannot use `CTRL + Backspace` to backwards delete a word and `CTRL + Delete` to forward delete a word.

**Expected behavior**
`CTRL + Backspace` should backward delete a whole word.
`CTRL + Delete` should forward delete a whole word.

**To reproduce**
Backwards delete:
```
* Open LM with meta+space
* Type "hello world!"
* Press `CTRL + Backspace`
```

Forwards delete:
```
* Open LM with meta+space
* Type "hello world!"
* Go with the cursor the the beginning of the word "world"
* Press `CTRL + Delete`
```

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 2004
 - Version: 0.1.4

**Additional context**
There could be other CTRL modifiers that edit input values this way, but I couldn't find any others during my quick search.

**Comment by sancarn** [comment]
Thanks Bram :) `alt+backspace`/`alt+delete` on Mac
